# Generated by Django 5.2.4 on 2025-07-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_remove_product_title_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
