# Generated by Django 5.2.4 on 2025-07-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Title',
        ),
    ]
