# Generated by Django 5.2.4 on 2025-07-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_name_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Title',
            new_name='name',
        ),
    ]
